### ISSUE TITLE
testing - functionality

### ISSUE THREAD

**Issue by EmolLi** [cherylyli/settlersOfAsia#6]
- [x]  rollDice  
    - [x] gate event -small bug will fix.
    - [x]  produce fish token (lake & fish port)
- [x]  buildSettlement
- [x]  upgradeToCity

- [x]      buildRoad
- [x]      'buildShip': 'buildShip',
- [x]      'endTurn': 'endTurn',
- [x]      'buildCityWall': 'buildCityWall',
- [x]      'buyCityImprovement': 'buyCityImprovement',
- [x]      'moveShip': 'moveShip',
- [x]    'tradeWithBank': 'tradeWithBank',
- [x]    'discardOneProgressCard': 'discardOneProgressCard',
- [x]      'stealCard': 'stealCard',
- [x]    'drawOneResourceCard': 'drawOneResourceCard',
- [x]      'giveAwayBoot': 'giveAwayBoot',
    - [x] basic functionality works, not sure whether the VP is accurate. 
- [x]     'drawOneProgressCard': 'drawOneProgressCard',
- [x]      'discardResourceCards': 'discardResourceCards',
- [x]     'chaseAwayThief': 'chaseAwayThief'
- [x]     'hireKnight': 'hireKnight',
- [x]      'activateKnight': 'activateKnight',
- [x]      'promoteKnight': 'promoteKnight',
- [x]      'moveKnight': 'moveKnight',
- [x] 'displaceKnight'
- [x]      "upgradeToMetropolis": 'upgradeToMetropolis',
    - [x] redistribute metropolis
- [x]      'chooseCityToBePillaged': 'chooseCityToBePillaged', 
- [x]     'moveRobber': 'moveRobber',
- [x]      'movePirate': 'movePirate',
- [x]     'spendFishToken': 'spendFishToken',

- [x]      'requestTrade': 'requestTrade',
- [x]     'acceptTrade': 'acceptTrade'
- [x]      'performTradeTransaction':'performTradeTransaction'

- [x]      'executeProgressCard': 'executeProgressCard'

**test case**
- [x] harbor trade (special & general)
    - [ ] FIXME:  harbor general and grain looks the same

- [ ] save Game (unimplemented)
- [ ] load Game (unimplemented)
- [ ] 6 test games (3/6)
- [ ] display longest road, defender of catan etc

**Comment by yz9** [comment]
stealCard, drawOneProgressCard, movePirate, moveRobber, drawOneResourceCard, discardResourceCards, chooseCityToBePillaged, 
- these commands should be made disabled from players until condition is met
