### ISSUE TITLE
testing - checkers

### ISSUE THREAD

**Issue by yz9** [cherylyli/settlersOfAsia#7]
- [ ]  rollDice
- [x]  buildSettlement
    - [ ]  must connect to road 
- [x]  upgradeToCity
- [x]      buildRoad
- [x]      'buildShip': 'buildShip',
- [x]      'endTurn': 'endTurn',
- [x]      'buildCityWall': 'buildCityWall',
- [x]      'buyCityImprovement': 'buyCityImprovement',

       - [ ] timeout too short, can barely see the succ / fail swal - fixed => now support pending swal
- [ ]      'moveShip': 'moveShip',
- [x]    'tradeWithBank': 'tradeWithBank',
     - [x]  harbour not working 
- [x]    'discardOneProgressCard': 'discardOneProgressCard',
- [x]      'stealCard': 'stealCard',
- [x]    'drawOneResourceCard': 'drawOneResourceCard',
    - [x]  disabled when condition not met. 
- [x]      'giveAwayBoot': 'giveAwayBoot',
    - [x] basic functionality works, not sure whether the VP is accurate. 
- [x]     'drawOneProgressCard': 'drawOneProgressCard',
    - [x]  disabled when condition not met. 
- [x]      'discardResourceCards': 'discardResourceCards',
    - [x]  disabled when condition not met. 
- [x]     'chaseAwayThief': 'chaseAwayThief'
- [x]     'hireKnight': 'hireKnight',
- [x]      'activateKnight': 'activateKnight',
- [x]      'promoteKnight': 'promoteKnight', - city improvement level constraint added (Fortress)
     - [x]  knight.hasBeenPromotedThisTurn
- [ ]      'moveKnight': 'moveKnight',
     - [x]   knight must be activated in the previous turn to do action: 'move knight' and 'chase away'
- [ ]      'displaceKnight' <---------
- [x]      "upgradeToMetropolis": 'upgradeToMetropolis',
    - [ ] redistribute metropolis
- [x]      'chooseCityToBePillaged': 'chooseCityToBePillaged', 
- [x]     'moveRobber': 'moveRobber',
    - [ ]  disabled when condition not met. 
- [x]      'movePirate': 'movePirate',
    - [ ]  disabled when condition not met. 
- [x]     'spendFishToken': 'spendFishToken',
    - [x]   robber/pirate not working, rest fine. 

- [ ]      'requestTrade': 'requestTrade',
- [ ]     'acceptTrade': 'acceptTrade'
- [ ]      'performTradeTransaction':'performTradeTransaction'
- [ ]      'executeProgressCard': 'executeProgressCard'

**Comment by cherylyli** [comment]
I'm able to roll dice in setup phase 1 and 2.

**Comment by cherylyli** [comment]
I'm able to build a settlement in setup phase 1 /2 when it's not my turn

**Comment by cherylyli** [comment]
In setup phase 2, game keeps telling me I can't build a settlement. I was able to finish this round (aka have one settlement and one city) only by upgrading the existing settlement to a city and then building another settlement.

**Comment by cherylyli** [comment]
Game shows setup phase 2 but the game logic thinks i'm still in setup phase 1
