### ISSUE TITLE
app.room.state and app.room.match.phase inconsistent

### ISSUE THREAD

**Issue by cherylyli** [cherylyli/settlersOfAsia#9]
In setup phase 1 and setup phase 2, the app.room.state and app.room.match.phase is inconsistent. 

When I finish setting up setup phase 1, the game still thinks it's in setup phase 1 even though it should've moved to setup phase 2. Therefore, in what should be setup phase 2, I can't place roads/ships or a city

**Comment by yz9** [comment]
@EmolLi
